### PR TITLE
Optimise PNGs with zopflipng

### PR DESCRIPTION
**Pull request by Rigo-V**
Thanks for developing this app, I love it!

I optimised all the PNGs in this repo with "zopflpng -m".
It optimises PNGs losslessly, meaning the images don't lose a single pixel of detail, while remaining fully backwards compatible. This should make the app even more lightweight :)
The entire repo got ~200kB smaller and the src/main/res directory shrunk by ~70kB.

### CODE REVIEW

**Comment by billthefarmer** [comment]
Thank you. I think it's done a good job on the PNG files in the docs and fastlane folders, but I'm not so sure about the app drawables. Have you checked whether the optimisation survives further optimisation during app build by the aapt tool?

[Create drawables from resource images](https://developer.android.com/guide/topics/graphics/drawables#drawables-from-images)

> **Note:** Image resources placed in the res/drawable/ directory may be automatically optimized with lossless image compression by the aapt tool during the build process. For example, a true-color PNG that doesn't require more than 256 colors may be converted to an 8-bit PNG with a color palette. This results in an image of equal quality but which requires less memory. As a result, the image binaries placed in this directory can change at build time. If you plan on reading an image as a bitstream in order to convert it to a bitmap, put your images in the res/raw/ folder instead, where the aapt tool doesn't modify them.

**Comment by billthefarmer** [comment]
Well it worked, the app size went down from 268K to 196K. Which is interesting because zopfli is Google code, you would expect them to use it aapt.

**Comment by Rigo-V** [comment]
Yeah, it sounds kinda weird that zopfli isn't even an option in aapt. But I get why it wouldn't be on by default, as it took my (2.4 GHz C2D) laptop about 10 minutes to optimise just these PNGs.

[https://programmer.group/optimize-package-size-png-section.html](https://programmer.group/optimize-package-size-png-section.html):
> AAPT2 for PNG image compression can be divided into three aspects:
> - Can RGB be converted to grayscale
> - Whether transparent channel can be deleted
> - Is it only 256 colors at most

If that page has it right, aapt only tries the cheapest (CPU-wise) strategies there are. And since zopfli has already tried all that (and more), aapt just rightfully gives up.

**Comment by billthefarmer** [comment]
So I cloned zopfli and built it and ran it on all my apps. And I noticed that one particular app where I used a later set of icons from the android dev site most of them were smaller already. So I ran it again with the -m switch and even then most were smaller or the same. And the -m switch made a very marginal difference to the screen images. So Google had something better than zopfli for small icon images most of the time a few years ago. And the -m switch probably isn't worth the extra time.
```shell
$ find . -name '*.png' -exec zopflipng -y -m {} {} \;
Optimizing ./fastlane/metadata/android/en-GB/images/featureGraphic.png
Input size: 27298 (26K)
Result size: 27264 (26K). Percentage of original: 99.875%
Result is smaller

Optimizing ./fastlane/metadata/android/en-GB/images/icon.png
Input size: 10613 (10K)
Result size: 10606 (10K). Percentage of original: 99.934%
Result is smaller

Optimizing ./fastlane/metadata/android/en-GB/images/phoneScreenshots/Screenshot_20190503-112113.png
Input size: 33963 (33K)
Result size: 33825 (33K). Percentage of original: 99.594%
Result is smaller

Optimizing ./fastlane/metadata/android/en-GB/images/phoneScreenshots/Screenshot_20190503-112128.png
Input size: 52187 (50K)
Result size: 52033 (50K). Percentage of original: 99.705%
Result is smaller

Optimizing ./fastlane/metadata/android/en-GB/images/phoneScreenshots/Screenshot_20190503-112220.png
Input size: 37338 (36K)
Result size: 37328 (36K). Percentage of original: 99.973%
Result is smaller

Optimizing ./fastlane/metadata/android/en-GB/images/phoneScreenshots/Screenshot_20190503-112320.png
Input size: 19945 (19K)
Result size: 19957 (19K). Percentage of original: 100.060%
Preserving original PNG since it was smaller

Optimizing ./fastlane/metadata/android/en-GB/images/phoneScreenshots/Screenshot_20190503-112330.png
Input size: 37351 (36K)
Result size: 37321 (36K). Percentage of original: 99.920%
Result is smaller

Optimizing ./ic_launcher.png
Input size: 10613 (10K)
Result size: 10606 (10K). Percentage of original: 99.934%
Result is smaller

Optimizing ./src/main/res/drawable-hdpi/ic_access_time_white_36dp.png
Input size: 762 (0K)
Result size: 874 (0K). Percentage of original: 114.698%
Preserving original PNG since it was smaller
```

**Comment by Rigo-V** [comment]
Or they could be using something crazy like `--iterations=2000 --filters=01234mepb --lossy_8bit --lossy_transparent`.
That could still make sense if they are distributing rarely-changing icons that will be used in many apps and downloaded who knows how many times from their Play Store.

Whatever they have, it's not applied very consistently. Just out of curiosity, I checked the logo in the top left corner of gmail, and it's compressed comparatively badly:
```shell
$ time zopflipng -y logo-gmail.png logo-gmail.png 
Optimizing logo-gmail.png
Input size: 4463 (4K)
Result size: 2574 (2K). Percentage of original: 57.674%
Result is smaller

zopflipng -y logo-gmail.png logo-gmail.png  7.87s user 0.03s system 99% cpu 7.911 total
```

**Comment by billthefarmer** [comment]
Thinking about it, bad move, the newer icons are all black and white and small, so it might be just something like a shorter header. Also the size of icons is small fry compared with the bloated support libraries they try to get developers to use if you follow the guidelines.

**Pull request merged**
